// AUTO-GENERATED by scripts/sync-formats.js — DO NOT EDIT
// Source of truth: formats.json

/**
 * Definition of a supported file format
 */
export interface FormatDefinition {
  /** Internal file type identifier, also used as settings key (e.g., 'mermaid', 'vega-lite') */
  fileType: string;
  /** File extensions without dot (e.g., ['mermaid', 'mmd']) */
  extensions: string[];
  /** VS Code language ID (e.g., 'mermaid', 'graphviz') */
  languageId: string;
  /** Code-block language identifiers that map to this fileType (e.g., ['plantuml', 'puml', 'wsd']). */
  codeBlockLanguages: string[];
  /** Whether this format is a diagram type (rendered visually). */
  isDiagram: boolean;
}

/**
 * All supported non-markdown formats.
 * Markdown (.md, .markdown) is always supported and not listed here.
 */
export const SUPPORTED_FORMATS: readonly FormatDefinition[] = [
  {
    "fileType": "slidev",
    "extensions": [
      "slides.md"
    ],
    "languageId": "markdown",
    "codeBlockLanguages": [
      "slidev"
    ],
    "isDiagram": false
  },
  {
    "fileType": "mermaid",
    "extensions": [
      "mermaid",
      "mmd"
    ],
    "languageId": "mermaid",
    "codeBlockLanguages": [
      "mermaid"
    ],
    "isDiagram": true
  },
  {
    "fileType": "plantuml",
    "extensions": [
      "plantuml",
      "puml"
    ],
    "languageId": "plantuml",
    "codeBlockLanguages": [
      "plantuml",
      "puml",
      "wsd"
    ],
    "isDiagram": true
  },
  {
    "fileType": "vega",
    "extensions": [
      "vega"
    ],
    "languageId": "vega",
    "codeBlockLanguages": [
      "vega"
    ],
    "isDiagram": true
  },
  {
    "fileType": "vega-lite",
    "extensions": [
      "vl",
      "vega-lite"
    ],
    "languageId": "vega",
    "codeBlockLanguages": [
      "vega-lite",
      "vegalite"
    ],
    "isDiagram": true
  },
  {
    "fileType": "dot",
    "extensions": [
      "gv",
      "dot"
    ],
    "languageId": "graphviz",
    "codeBlockLanguages": [
      "dot",
      "graphviz"
    ],
    "isDiagram": true
  },
  {
    "fileType": "infographic",
    "extensions": [
      "infographic"
    ],
    "languageId": "infographic",
    "codeBlockLanguages": [
      "infographic"
    ],
    "isDiagram": true
  },
  {
    "fileType": "canvas",
    "extensions": [
      "canvas"
    ],
    "languageId": "canvas",
    "codeBlockLanguages": [
      "canvas"
    ],
    "isDiagram": true
  },
  {
    "fileType": "drawio",
    "extensions": [
      "drawio"
    ],
    "languageId": "drawio",
    "codeBlockLanguages": [
      "drawio"
    ],
    "isDiagram": true
  }
];

// =============================================================================
// Derived lookup tables (built once from SUPPORTED_FORMATS)
// =============================================================================

/** Diagram formats only (excludes slidev and other non-diagram formats). */
export const DIAGRAM_FORMATS: readonly FormatDefinition[] =
  SUPPORTED_FORMATS.filter(f => f.isDiagram);

/** All code-block language identifiers recognized as diagrams (lowercased). */
export const DIAGRAM_CODE_BLOCK_LANGUAGES: readonly string[] =
  Array.from(new Set(DIAGRAM_FORMATS.flatMap(f => f.codeBlockLanguages.map(l => l.toLowerCase()))));

/**
 * Map code-block language identifier (lowercased) → fileType.
 * Includes aliases such as 'wsd' → 'plantuml', 'vegalite' → 'vega-lite', 'graphviz' → 'dot'.
 * Use this to resolve any fence-block or host-page code-block language to the internal render type.
 */
export const CODE_BLOCK_LANGUAGE_MAP: Readonly<Record<string, string>> = (() => {
  const map: Record<string, string> = {};
  for (const f of DIAGRAM_FORMATS) {
    for (const lang of f.codeBlockLanguages) {
      map[lang.toLowerCase()] = f.fileType;
    }
  }
  return map;
})();

/** Set of all code-block language identifiers (lowercased) for fast membership checks. */
export const DIAGRAM_CODE_BLOCK_LANGUAGE_SET: ReadonlySet<string> =
  new Set(DIAGRAM_CODE_BLOCK_LANGUAGES);

/** Map file extension (without dot) → fileType. Includes 'md'/'markdown' → 'markdown'. */
export const EXTENSION_TO_FILE_TYPE: Record<string, string> = { md: 'markdown', markdown: 'markdown' };
for (const f of SUPPORTED_FORMATS) {
  for (const ext of f.extensions) {
    EXTENSION_TO_FILE_TYPE[ext] = f.fileType;
  }
}

/** Map dotted extension (e.g. '.mermaid') → fileType */
export const DOT_EXTENSION_TO_FILE_TYPE: Record<string, string> = {};
for (const f of SUPPORTED_FORMATS) {
  for (const ext of f.extensions) {
    DOT_EXTENSION_TO_FILE_TYPE[`.${ext}`] = f.fileType;
  }
}

/** All supported extensions with dot, including markdown */
export const ALL_SUPPORTED_EXTENSIONS: readonly string[] = [
  '.md', '.markdown',
  ...SUPPORTED_FORMATS.flatMap(f => f.extensions.map(e => `.${e}`)),
].sort((a, b) => b.length - a.length);

/** All supported extensions without dot, excluding markdown */
export const ALL_FORMAT_EXTENSIONS: readonly string[] =
  SUPPORTED_FORMATS.flatMap(f => f.extensions);

/** Unique VS Code language IDs (includes 'markdown') */
export const SUPPORTED_LANGUAGE_IDS: readonly string[] = [
  'markdown',
  ...Array.from(new Set(SUPPORTED_FORMATS.map(f => f.languageId))),
];

/** Default SupportedExtensions object (all enabled, keyed by fileType) */
export function getDefaultSupportedExtensions(): SupportedExtensions {
  const result: SupportedExtensions = {};
  for (const f of SUPPORTED_FORMATS) {
    result[f.fileType] = true;
  }
  return result;
}

/** SupportedExtensions type – keys are fileType values */
export type SupportedExtensions = Record<string, boolean>;
