// AUTO-GENERATED by scripts/sync-settings.js — DO NOT EDIT
// Source of truth: settings-schema.json
//
// To change a default/type/validation: edit settings-schema.json and run
// `node scripts/sync-settings.js`. See plans/config-centralization-plan.md.

/** All available setting keys (excludes CLI-only entries). */
export type SettingKey =
  | 'themeId'
  | 'frontmatterDisplay'
  | 'tableLayout'
  | 'imageLayout'
  | 'diagramLayout'
  | 'tableMergeEmpty'
  | 'firstLineIndent'
  | 'preferredLocale'
  | 'docxHrDisplay'
  | 'docxEmojiStyle'
  | 'swapPanelSide'
  | 'readerSidebarWidth';

/** Setting value types mapped by key. */
export interface SettingTypes {
  /** Theme preset id (themes/presets/<id>.json). Exposed as `theme` in DEFAULT_RENDER_SETTINGS (CLI) and `theme` in the mobile settings service. */
  themeId: string;
  /** Frontmatter display: hide | table | raw. */
  frontmatterDisplay: 'hide' | 'table' | 'raw';
  /** Table alignment. */
  tableLayout: 'left' | 'center' | 'center-full-width';
  /** Standalone image alignment. */
  imageLayout: 'left' | 'center';
  /** Diagram/chart alignment. */
  diagramLayout: 'left' | 'center';
  /** Merge empty table cells. */
  tableMergeEmpty: boolean;
  /** First-line indent in characters (0 = none). */
  firstLineIndent: number;
  /** Extension UI locale. Mobile uses 'system' as its default (device locale). */
  preferredLocale: string;
  /** HR display mode in DOCX export. */
  docxHrDisplay: 'pageBreak' | 'line' | 'hide';
  /** Emoji style in DOCX export. */
  docxEmojiStyle: 'apple' | 'windows' | 'system';
  /** Swap the side of the side panel (desktop platforms). */
  swapPanelSide: boolean;
  /** Reader sidebar width in pixels. */
  readerSidebarWidth: number;
}

/** Default values for all shared settings. */
export const DEFAULT_SETTINGS: SettingTypes = {
  themeId: 'default',
  frontmatterDisplay: 'hide',
  tableLayout: 'center',
  imageLayout: 'center',
  diagramLayout: 'center',
  tableMergeEmpty: true,
  firstLineIndent: 2,
  preferredLocale: 'auto',
  docxHrDisplay: 'hide',
  docxEmojiStyle: 'system',
  swapPanelSide: false,
  readerSidebarWidth: 280,
};

/**
 * Default render/layout settings for the documd CLI and render pipeline.
 * `theme`/`language` are deliberately separate from the extension settings
 * (`themeId`/`preferredLocale`): one is the rendered document, the other the UI.
 */
export const DEFAULT_RENDER_SETTINGS = {
  /** Theme preset id (themes/presets/<id>.json). Exposed as `theme` in DEFAULT_RENDER_SETTINGS (CLI) and `theme` in the mobile settings service. */
  theme: 'default',
  /** Language code of the rendered/exported document (CLI only, deliberate separate from preferredLocale which is the extension UI locale). */
  language: 'en',
  /** Frontmatter display: hide | table | raw. */
  frontmatterDisplay: 'hide',
  /** Table alignment. */
  tableLayout: 'center',
  /** Standalone image alignment. */
  imageLayout: 'center',
  /** Diagram/chart alignment. */
  diagramLayout: 'center',
  /** Merge empty table cells. */
  tableMergeEmpty: true,
  /** First-line indent in characters (0 = none). */
  firstLineIndent: 2,
} as const;

/**
 * Normalize a raw (possibly invalid/absent) setting value against the schema.
 * Returns the value if valid, otherwise the schema default.
 * This is the SINGLE fallback entry point — platforms must not re-implement
 * their own per-key fallback logic.
 */
export function normalizeSetting<K extends SettingKey>(
  key: K,
  raw: unknown,
): SettingTypes[K];
export function normalizeSetting(
  key: SettingKey,
  raw: unknown,
): unknown {
  switch (key) {
    case 'themeId':
      return (typeof raw === 'string') ? raw : 'default';
    case 'frontmatterDisplay':
      return (raw === 'hide' || raw === 'table' || raw === 'raw') ? raw : 'hide';
    case 'tableLayout':
      return (raw === 'left' || raw === 'center' || raw === 'center-full-width') ? raw : 'center';
    case 'imageLayout':
      return (raw === 'left' || raw === 'center') ? raw : 'center';
    case 'diagramLayout':
      return (raw === 'left' || raw === 'center') ? raw : 'center';
    case 'tableMergeEmpty':
      return (typeof raw === 'boolean') ? raw : true;
    case 'firstLineIndent':
      return (typeof raw === 'number' && raw >= 0 && raw <= 4) ? raw : 2;
    case 'preferredLocale':
      return (typeof raw === 'string') ? raw : 'auto';
    case 'docxHrDisplay':
      return (raw === 'pageBreak' || raw === 'line' || raw === 'hide') ? raw : 'hide';
    case 'docxEmojiStyle':
      return (raw === 'apple' || raw === 'windows' || raw === 'system') ? raw : 'system';
    case 'swapPanelSide':
      return (typeof raw === 'boolean') ? raw : false;
    case 'readerSidebarWidth':
      return (typeof raw === 'number' && raw >= 160 && raw <= 600) ? raw : 280;
    default:
      throw new Error(`Unknown setting key: ${String(key)}`);
  }
}
