// AUTO-GENERATED by scripts/sync-settings.js — DO NOT EDIT
// Source of truth: settings-schema.json
//
// To change a default: edit settings-schema.json and run
// `node scripts/sync-settings.js`. See plans/config-centralization-plan.md.

// Shared setting defaults for the mobile (Flutter) settings service.
// Keys use the mobile storage names (dartKey) where they differ from the TS key.

const kThemeDefault = 'default';
const kFrontmatterDisplayDefault = 'hide';
const kTableLayoutDefault = 'center';
const kImageLayoutDefault = 'center';
const kDiagramLayoutDefault = 'center';
const kTableMergeEmptyDefault = true;
const kFirstLineIndentDefault = 2;
const kLocaleDefault = 'system';
const kHrDisplayDefault = 'hide';
const kEmojiStyleDefault = 'system';
const kSwapPanelSideDefault = false;
const kReaderSidebarWidthDefault = 280;
